Repository huequica/DiscordTrashedDiver, pull requests merged in 2024-05, with the labels that each got.

#225 Twitterクライアントを上部から渡すことでシングルトン化した
  src/actions/leakMessage.ts
  src/actions/removeTweet.ts
  src/events.ts
  src/index.ts
Labels: brashup

#228 Add logger to leakMessage's some implementation
  src/actions/leakMessage.ts
Labels: leakMessage

#229 Add MessageContent Intent to config
  src/config/env.ts
Labels: BUG, leakMessage
